// <auto-generated />
namespace StudentLibrary.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class Change_username : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_username));
        
        string IMigrationMetadata.Id
        {
            get { return "201912231135116_Change_username"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
